name:                shellout
version:             0.1.0.0
github:              "loganmac/shellout"
license:             BSD3
author:              "Logan McPhail"
maintainer:          "logan.airnomad@gmail.com"
copyright:           "2018 Logan McPhail"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/loganmac/shellout#readme>

dependencies:
- async
- base >= 4.7 && < 5
- stm
- text
- typed-process

library:
  source-dirs: src

executables:
  example:
    main:                Main.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shellout
